# Generated by Django 4.1.4 on 2022-12-08 14:23

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('monday', models.DateField()),
                ('next_monday', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('monday__week_day', 2)), name='ensure_monday'),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.CheckConstraint(check=models.Q(('next_monday', django.db.models.expressions.CombinedExpression(models.F('monday'), '+', models.Value(datetime.timedelta(days=7))))), name='ensure_7_days_gap', violation_error_message='next_monday must be exactly 7 days greater monday'),
        ),
    ]
