from .common import ExtendedObjectPermission, StaffManagedObjectPermission, IsSuperuser, IsSuperuserOrAuthenticatedReadOnly
from .user import UserAccessPermission, UserRelationshipReadOnlyAccessPermission
from .lab import LabAccessPermission
from .course import CourseAccessPermission
from .group import GroupAccessPermission, GroupStudentAccessPermission
from .session import Session
from .attendance import BaseAttendanceAccessPermission, StudentAttendanceAccessPermission, TeacherAttendanceAccessPermission
